jsI18n.addLocale("fr",{
"m-dash" : "Tableau de bord",
"m-file" : "Fichiers",
"m-set" : "Paramètres",
"s-ap" : "Wifi Point d'accès",
"s-cl" : "Client Wifi",
"s-rec" : "Récepteur",
"m-lang" : "Langue",
"l-wap" : "Wifi Access Point",
"l-saved" : "Paramètres sauvegardés",
"l-ssid" : "SSID / Nom",
"l-pass" : "Mot de passe",
"l-auth" : "Authentification",
"l-save" : "Enregistrer",
"l-cancel" : "Annuler",
"l-wcl" : "Wifi Client",
"l-setup" : "Configuration du récepteur",
"l-frew" : "Fréquence (Hz)",
"l-bw" : "Bande passante",
"l-sf" : "Facteur d'étalement",
"l-cr" : "Taux de codage",
"l-lnb" : "Tension LNB",
"l-lo" : "Fréquence oscillateur (MHz)",
"l-loeng" : "Activation de l'oscillateur",
"l-diseq" : "Activer diseq (22kHz)",
"l-fres" : "Réinitialisation d'usine",
"f-title" : "Visionneuse de fichiers",
"f-nodata" : "Pas encore de données...",
"l-close" : "Fermer",
"d-welcome" : "Bienvenue chez Othernet",
"d-sub" : "UNE ÉMISSION POUR L'ÂGE NUMÉRIQUE",
"d-1" : "Informations sur le périphérique",
"d-1-1" : "Version du matériel",
"d-1-2" : "Version du firmware",
"d-1-3" : "Adresse IP",
"d-2" : "État de la mémoire",
"d-2-1" : "Free Heap",
"d-2-2" : "Min Free Heap",
"d-2-3" : "SPIram libre",
"d-3" : "État de la carte SD",
"d-3-1" : "Capacité",
"d-3-2" : "Free",
"d-3-3" : "Used",
"d-4" : "CPU Load",
"d-5" : "LNB Status",
"d-5-1" : "LNB activé",
"d-5-2" : "LNB in range",
"d-5-3" : "LNB connecté",
"d-5-4" : "Tension LNB",
"d-5-5" : "Décalage FREQ",
"d-6" : "État du récepteur",
"d-7" : "Stats du récepteur",
"d-7-1" : "RSSI",
"d-7-2" : "Paquets reçus",
"d-7-3" : "Erreurs CRC",
"d-7-4" : "Erreurs d'en-tête",
"d-8" : "Info fichier",
"d-8-1" : "Nom",
"d-8-2" : "Progression",
"fb-title" : "Navigateur de fichiers",
"fb-sub" : "Parcourir tous les fichiers que vous avez téléchargés depuis le ciel",
"fb-format" : "Formater la carte SD",
"footer" : "Contribuer sur Github"}) ;