jsI18n.addLocale("pot",{
"m-dash":"Dashboard",
"m-file":"Files",
"m-set":"Settings",
"s-ap":"Wifi AP",
"s-cl":"Wifi Client",
"s-rec":"Receiver",
"m-lang":"Language",
"l-wap":"Wifi Access Point",
"l-saved":"Settings Saved",
"l-ssid":"SSID / Name",
"l-pass":"Password",
"l-auth":"Authentication",
"l-save":"Save",
"l-cancel":"Cancel",
"l-wcl":"Wifi Client",
"l-setup":"Receiver Setup",
"l-frew":"Frequency (Hz)",
"l-bw":"Bandwidth",
"l-sf":"Spreading factor",
"l-cr":"Coding rate",
"l-lnb":"LNB voltage",
"l-lo":"LO frequency (MHz)",
"l-loeng":"Enable LO",
"l-diseq":"Enable diseq (22kHz)",
"f-title":"File Viewer",
"f-nodata":"No data Yet...",
"l-close":"Close",
"d-welcome":"Welcome to Othernet",
"d-sub":"A BROADCAST FOR THE DIGITAL AGE",
"d-1":"Device Information",
"d-1-1":"Hardware Version",
"d-1-2":"Firmware Version",
"d-1-3":"IP Address",
"d-2":"Memory Status",
"d-2-1":"Free Heap",
"d-2-2":"Min Free heap",
"d-2-3":"Free SPIram",
"d-3":"SD Card Status",
"d-3-1":"Capacity",
"d-3-2":"Free",
"d-3-3":"Used",
"d-4":"CPU Load",
"d-5":"LNB Status",
"d-5-1":"LNB enabled",
"d-5-2":"LNB in range",
"d-5-3":"LNB connected",
"d-5-4":"LNB voltage",
"d-5-5":"FREQ offset",
"d-6":"Receiver Status",
"d-7":"Receiver Stats",
"d-7-1":"RSSI",
"d-7-2":"Packets Received",
"d-7-3":"CRC Errors",
"d-7-4":"Header Errors",
"d-8":"File info",
"d-8-1":"Name",
"d-8-2":"Progress",
"fb-title":"File Browser",
"fb-sub":"Browse All files you Downloaded from the Sky",
"fb-format":"Format SD Card",
"footer":"Contribute on Github"});